# Generated by Django 3.1.6 on 2021-02-10 13:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 13, 46, 40, 723330, tzinfo=utc), verbose_name='Publicación'),
        ),
    ]
